# Generated by Django 3.2.8 on 2021-11-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section1_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateField(auto_created=True)),
                ('check1', models.BooleanField(default=False)),
                ('aQty1', models.FloatField()),
                ('aItemID1', models.CharField(max_length=25)),
                ('check2', models.BooleanField(default=False)),
                ('aItemID2', models.CharField(max_length=25)),
                ('aQty2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Section1_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateField(auto_created=True)),
                ('check1', models.BooleanField(default=False)),
                ('aItemID1', models.CharField(max_length=25)),
                ('itemID1', models.CharField(max_length=25)),
                ('check2', models.BooleanField(default=False)),
                ('aItemID2', models.CharField(max_length=25)),
                ('aQty2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Section1_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateField(auto_created=True)),
                ('check1', models.BooleanField(default=False)),
                ('aItemID1', models.CharField(max_length=25)),
                ('check2', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
