# Generated by Django 3.2.8 on 2021-11-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section1_1',
            name='TimeStamp',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
