# Generated by Django 3.2.8 on 2021-11-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0002_alter_section1_1_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section1_1',
            name='TimeStamp',
        ),
        migrations.AddField(
            model_name='section1_1',
            name='timestamp',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
